### ISSUE TITLE
Two IMU-LiDAR extrinsics in yaml

### ISSUE THREAD

**Issue by cmakelabs** [minwoo0611/MA-LIO#29]
For `mapping/extrinsic_T`, and `mapping/extrinsic_R` in the [`yaml`](https://github.com/minwoo0611/MA-LIO/blob/main/MA_LIO/config/City.yaml) files available in the `config` folder, there is only:
one translation matrix and one rotation matrix, like this for example:

```
    extrinsic_T: [ 0.215, 0, 0.018, 
                   -1.2574, 0.413, 0.0324,
                   -1.306, -0.361, 0.042  ]
    extrinsic_R: [ 1, 0, 0, 0,
                   0.6965018, -0.0037329, -0.0038405, 0.717535, 
                   0.0074645, 0.0000044, -0.0005919, -0.999972]
```
but in the [image](https://github.com/minwoo0611/MA-LIO/blob/main/figs/fig_output.png?raw=true) I can see that it is possible to specify for each LIDAR the matrices `extrinsic_T` and `extrinsic_R`  with respect to `IMU`, this means I would have for two LIDARs two translation matrices and two rotation matrices, Could you please tell how to specify that in the `yaml` file?

**Comment by minwoo0611** [comment]
Hello @cmakelabs,

In the YAML files within the config folder, each row of `extrinsic_T` corresponds to the translation parameters (x, y, z) for each LIDAR with respect to the IMU. Similarly, each row of `extrinsic_R` corresponds to the rotation parameters (qw, qx, qy, qz) for each LIDAR with respect to the IMU.

For example, the given matrices translate as follows:
- IMU to LIDAR1 translation: [0.215, 0, 0.018]
- IMU to LIDAR2 translation: [-1.2574, 0.413, 0.0324]
- IMU to LIDAR3 translation: [-1.306, -0.361, 0.042]
- IMU to LIDAR1 rotation: [1, 0, 0, 0]
- IMU to LIDAR2 rotation: [0.6965018, -0.0037329, -0.0038405, 0.717535]
- IMU to LIDAR3 rotation: [0.0074645, 0.0000044, -0.0005919, -0.999972]

Ensure the order of these rows corresponds to your LIDAR configuration, which might look like this:

```yaml
lid_topic: ["/os_cloud_node/points", "/livox/avia/points", "/livox/tele/points"]
lid_type: [3, 1, 1]           # 1-Livox, 2-Velodyne, 3-Ouster
N_SCANS: [128, 8, 8]
point_filter_num: [8, 4, 4]
```

This way, each LIDAR's translation and rotation matrices are properly specified with respect to the IMU.

**Comment by minwoo0611** [comment]
Hello @cmakelabs,

Thank you for your question. In the YAML file, you should have one `extrinsic_T` and one `extrinsic_R`, and the values for all the LIDARs should be included within these matrices in the correct order.

For example, if you have two LIDARs, you would specify their translation and rotation matrices in sequence within `extrinsic_T` and `extrinsic_R`, like this:

```yaml
extrinsic_T: [ 0.215, 0, 0.018, 
               -1.2574, 0.413, 0.0324 ]
extrinsic_R: [ 1, 0, 0, 0,
               0.6965018, -0.0037329, -0.0038405, 0.717535 ]
```

The order of the parameters in `extrinsic_T` and `extrinsic_R` should correspond to the order of your LIDARs as defined in your configuration. This way, the parser will correctly associate each set of translation and rotation parameters with the respective LIDAR based on their order in the file.

Ensure that the LIDAR configuration matches the order of the matrices:

```yaml
lid_topic: ["/os_cloud_node/points", "/livox/avia/points"]
lid_type: [3, 1]           # 1-Livox, 2-Velodyne, 3-Ouster
N_SCANS: [128, 8]
point_filter_num: [8, 4]
```

By doing this, the parser will understand which parameters in the YAML file correspond to which LIDAR, based solely on the order in the file. This ensures that all parameters are correctly associated with the respective LIDARs.
